main:
  steps:
    - initiate-data-processing:
        call: http.post
        args:
          url: https://us-central1-mlops-vertexai-project.cloudfunctions.net/process_data
          body:
            bucket: mlops-vertexai-project-bucket
            file: data.csv
        result: data_processing_result

    - wait-for-training:
        call: sys.sleep
        args:
          seconds: 30

    - initiate-model-serving:
        call: http.post
        args:
          url: https://us-central1-mlops-vertexai-project.cloudfunctions.net/ml_model_predict
          body:
            features: [3, 1, 25.0, 0, 0, 7.25, 2]
        result: model_prediction

    - return_prediction:
        return: ${model_prediction.body}
